%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=quarkus_test
%prod.quarkus.datasource.password=quarkus_test
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost/quarkus_test
%prod.quarkus.datasource.jdbc.max-size=8
%prod.quarkus.datasource.jdbc.min-size=2
quarkus.datasource.devservices.port=5432
# KEYCLOACK
quarkus.oidc.auth-server-url=http://127.0.0.1:8080/realms/dev
quarkus.oidc.client-id=quarkus-tocloc
quarkus.oidc.credentials.secret=qMN9s5vnxiTtlmAABtlXfFmeweuWdvO8
quarkus.log.category."io.quarkus.security".level=DEBUG
quarkus.log.category."io.quarkus.oidc".level=DEBUG
quarkus.log.category."io.quarkus.oidc.runtime".level=DEBUG
quarkus.log.category."io.quarkus.oidc.runtime.OidcUtils".level=DEBUG
quarkus.log.category."io.quarkus.oidc.runtime.OidcConfig".level=DEBUG
quarkus.log.category."io.quarkus.oidc.runtime.OidcTenantConfig".level=DEBUG
quarkus.log.category."io.quarkus.keycloak".level=DEBUG

#policy
quarkus.keycloak.policy-enforcer.enable=true
quarkus.keycloak.policy-enforcer.lazy-load-paths=false
#quarkus.keycloak.policy-enforcer.paths.1.paths=/local/*
#quarkus.keycloak.policy-enforcer.paths.1.enforcement-mode=DISABLED

quarkus.http.port=8081
# quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=import.sql


# Ativar suporte ao RESTEasy Reactive e validação
quarkus.resteasy-reactive.enable-multipart=true

# Nível de log para depuração de validação
quarkus.log.category."org.hibernate.validator".level=DEBUG


# Ativar suporte a CORS
quarkus.http.cors=true

# Origem permitida (apenas o frontend rodando na porta 3000)
quarkus.http.cors.origins=http://localhost:3000

# Métodos HTTP permitidos
quarkus.http.cors.methods=GET, POST, PUT, DELETE

# Cabeçalhos permitidos
quarkus.http.cors.headers=Content-Type, Authorization

# Cabeçalhos expostos
quarkus.http.cors.exposed-headers=Content-Disposition

# Permitir credenciais (se necessário)
quarkus.http.cors.allow-credentials=true

